# Generated by Django 5.2.1 on 2025-05-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamdata',
            name='start_time',
        ),
        migrations.AddField(
            model_name='streamdata',
            name='game_name',
            field=models.CharField(default='Uknown Game', max_length=255),
        ),
        migrations.AddField(
            model_name='streamdata',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamdata',
            name='thumbnail_url',
            field=models.URLField(default='Uknown Image'),
        ),
        migrations.AddField(
            model_name='streamdata',
            name='title',
            field=models.CharField(default='Uknown Title', max_length=255),
        ),
        migrations.AddField(
            model_name='streamdata',
            name='user_id',
            field=models.CharField(default='Uknown User ID', max_length=255),
        ),
        migrations.AddField(
            model_name='streamdata',
            name='user_name',
            field=models.CharField(default='Uknown Username', max_length=255),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='viewer_count',
            field=models.IntegerField(default=0),
        ),
    ]
