# Generated by Django 5.2.1 on 2025-06-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='streamdata',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
