# Generated by Django 5.2.1 on 2025-05-28 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='favorite_games',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.game'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='favorite_streamers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.streamdata'),
        ),
    ]
