# Generated by Django 5.2.1 on 2025-05-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_streamdata_game_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamdata',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
