# Generated by Django 5.2.1 on 2025-05-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_streamdata_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamdata',
            name='viewer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
