# Generated by Django 5.2.1 on 2025-05-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_streamdata_viewer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamdata',
            name='streamer_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
