# Generated by Django 5.2.1 on 2025-05-30 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_favorite_favorite_games_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='streamdata',
            unique_together={('streamer_id', 'user_id')},
        ),
    ]
