# Generated by Django 5.2.1 on 2025-05-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_favoritegame_favoritestreamer_delete_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='streamdata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
